[font]
size = 12.5

builtin_box_drawing = true

normal = { family = "VictorMono Nerd Font Mono", style = "Regular" }
bold = { family = "VictorMono Nerd Font Mono", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
bold_italic = { family = "VictorMono Nerd Font Mono", style = "Bold Italic" }
